---
- name: "Requete dans une base donnée"
  hosts: bdd1
  gather_facts: no
  tasks:
    - name: "compter le nombre de pase dans le Wiki"
      count_page:
        db_name: "mediawiki"
        request: "select count(*) from page;"
      register: resultat
    - debug: var=resultat
